import NavbarComponent from "@/components/NavbarComponent";
import "./globals.css";
import SidebarComponent from "@/components/SidebarComponent";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-SFProDisplay">
        {/* <div className="flex ">
        <div className=" w-[20%]"><SidebarComponent/></div>
          <div className="w-[80%]"><NavbarComponent/></div>
          
        </div> */}
        

        {children}
      </body>
    </html>
  );
}
